#!/bin/sh

REST='\e[0m'
GREEN='\e[0;32m'
BGREEN='\e[7;32m'
BRED='\e[7;31m'
Cyan='\033[0;36m'
BCyan='\033[7;36m'

printd ()
{            
    
    if [ -z "$2" ];then COLOR=$REST
    elif [ "$2" = "G" ];then COLOR=$GREEN
    elif [ "$2" = "BG" ];then COLOR=$BGREEN
    elif [ "$2" = "R" ];then COLOR=$BRED
    elif [ "$2" = "Cy" ];then COLOR=$Cyan
    elif [ "$2" = "BCy" ];then COLOR=$BCyan
    else COLOR=$REST
    fi

    time=$(date +"%T")
    printf "${time} ${COLOR}${1}${REST} \n"
}

# Verify USB
res=$(inno_verify)
echo "${res}"

flag=$(echo "${res}" | grep FAILED )
if [ -z "${flag}" ];then
    # Entry Point
    printf "Entry: %s\n" "$@"
    exec "$@"
else
    echo "Exit"
    exit
fi